name: My cool Snowflake workflow
on: [workflow_dispatch]

permissions:
  id-token: write # Required to fetch an OIDC token
  contents: read

jobs:
  my-cool-job:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.AZURE_PRINCIPAL_ID }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_AUTHENTICATOR: OAUTH
      SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE: SNOWSQL_RL
    
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true
  
    - name: Get Snowflake access token
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          access_token=$(az account get-access-token --scope ${{ secrets.OAUTH_SERVER_IDENTIFIER_URI }}/.default --query accessToken -o tsv)
          echo "::add-mask::$access_token"
          echo "SNOWFLAKE_CONNECTIONS_DEFAULT_TOKEN=$access_token" >> "$GITHUB_ENV"  

    - name: Create config.toml
      run: |
        cat << EOF > config.toml
        default_connection_name = "default"
        
        [connections]
        [connections.default]
        user = ""
        EOF

    - name: Install Snowflake CLI
      uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: latest
        default-config-file-path: config.toml

    - name: Execute Snowflake CLI command
      run: |
        snow --version
        snow connection test